<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Log\Api\Representation\LogRepresentation[] $logs
 * @var \Log\Api\Representation\LogRepresentation[] $resources
 * @var \Omeka\Form\ConfirmForm $formDeleteSelected
 * @var \Omeka\Form\ConfirmForm $formDeleteAll
 * @var \Log\Form\QuickSearchForm $formSearch
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$hyperlink = $plugins->get('hyperlink');
$url = $plugins->get('url');
$sortLink = $plugins->get('sortLink');
$assetUrl = $plugins->get('assetUrl');
$i18n = $plugins->get('i18n');

$this->htmlElement('body')->appendAttribute('class', 'sitelog browse');

$this->headLink()
    ->appendStylesheet($assetUrl('css/log.css', 'SiteLog'));

$sortHeadings = [
    [
        'label' => $translate('Date'),
        'value' => 'created',
    ],
    [
        'label' => $translate('id'),
        'value' => 'id',
    ],
];

?>

<?= $this->pageTitle('', 1, $translate('SiteLog')) ?>
<?= $this->logSearchFilters() ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<div id="page-actions">
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if (count($sitelogs)): ?>
<form method='post' id="batch-form" class="disable-unsaved-warning">
    <div class="batch-inputs">
        
        <div class="batch-actions">
            <input type="hidden" name="query" class="batch-query" value="<?= $escapeAttr(json_encode($this->params()->fromQuery())) ?>">
            
        </div>
    </div>

    <table class="tablesaw batch-edit" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $sortLink($translate('Reference'), 'reference') ?></th>
                <th><?= $sortLink($translate('Page'), 'page') ?></th>
                <th><?= $sortLink($translate('Resources'), 'resources') ?></th>
                <th><?= $sortLink($translate('Context'), 'url') ?></th>
                <th><?= $sortLink($translate('Ip'), 'ip') ?></th>
                <th><?= $sortLink($translate('Date'), 'date') ?></th>
                
            </tr>
        </thead>
        <tbody>
        <?php foreach ($sitelogs as $sitelog): ?>
        <tr>
            <td class="webui-popover-parent" style="word-break: break-all;">
                <span class="log-message">
                    <span class="log-message-truncated truncate"><?php echo $sitelog->getJsonLd()['o:reference']?></span>
                </span>
            </td>
            <td><?php echo $sitelog->getJsonLd()['o:page_slug']?></td>
            <td><?php echo $sitelog->getJsonLd()['o:resources_id']?></td>
            <td><?php echo $sitelog->getJsonLd()['o:context']?></td>
            <?php $userip = $sitelog->getJsonLd()['o:user_ip']?>
            <td><?php echo substr($userip,0,3) . '.***.***.***' ?></td>
            <td><?= $i18n->dateFormat($sitelog->created(), 'medium', 'medium') ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div id="sidebar" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?= $translate('Omeka could not find any logs, or they are saved in another place.') ?></p>
</div>

<?php endif; ?>

